# Generated by Django 5.0.6 on 2024-05-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
